### ISSUE TITLE
sqlite variant 类型无法存QRect数据

### ISSUE THREAD

**Issue by Kevinzhang35** [daonvshu/QtDao#3]
需要在数据库中保存QRect数据的时候，写入数据库后的值为空。

**Comment by daonvshu** [comment]
参考使用自定义类型存储[https://daonvshu.github.io/QtDao/pages/functions/08_custom/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B](https://daonvshu.github.io/QtDao/pages/functions/08_custom/#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%9E%8B)
